### ISSUE TITLE
AWS Proton

### ISSUE THREAD

**Issue by regicsolutions** [awslabs/app-development-for-backstage-io-on-aws#13]
This was long overdue, excellent job on this 👏

Wondering where [AWS Proton](https://aws.amazon.com/blogs/containers/provisioning-infrastructure-using-the-aws-proton-open-source-backstage-plugin/) fits into this solution.

**Comment by z-sourcecode** [comment]
Thanks @regicsolutions we appreciate your feedback.

This is designed to address enterprise needs for scaling application developers across multiple AWS environments and teams. The frontend and the Cloud backend of this solution is completely customizable so customers can articulate how apps are provisioned, what resources they need and design an operational layer for these changes.
