### ISSUE TITLE
VPC and EIP limits exceeds on a brand new aws account

### ISSUE THREAD

**Issue by gowthamshankar99** [awslabs/app-development-for-backstage-io-on-aws#18]
it looks like the ```make deploy```  cdk creates more than 5 EIPs and the default service quota limit for EIP is 5 per region.

Can we add somewhere in the documentation regarding this ? this could avoid any failures that may happen.

<img width="745" alt="image" src="https://github.com/awslabs/app-development-for-backstage-io-on-aws/assets/28915789/c274c5f0-f6db-4b34-971d-11cfe499ce9f">

**Comment by z-sourcecode** [comment]
Thanks you for your feedback and contribution @gowthamshankar99 . On the next release this issue won't be a problem as we will support dynamic provisioning of environments.
