### ISSUE TITLE
Feature Request: AWS Service Catalog Integration

### ISSUE THREAD

**Issue by regicsolutions** [awslabs/app-development-for-backstage-io-on-aws#21]
For large enterprises already making use of AWS’s Service Catalog it would great to support a  integration pattern with the Backstage Scaffolder

Was thinking this could be very similar or even build on top of the solution Verizon shared with the ServiceNow catalog documented [here](https://aws.amazon.com/blogs/mt/enhancing-configuration-management-at-verizon-using-aws-systems-manager/) using a [AWS  Service Management Connector](https://docs.aws.amazon.com/smc/latest/ag/overview.html) for Backstage for enterprises already using ServiceNow and looking to implement a more curated developer experience when a developer clicks Create + they could have a sub-page called AWS Service Catalog that would display something similar to this shopping cart type experience: 

![IMG_0660](https://github.com/awslabs/app-development-for-backstage-io-on-aws/assets/6157895/0e1dfb41-dbe6-4786-ac76-e1c21eaef5ce)

**Comment by regicsolutions** [comment]
> Thanks @regicsolutions.
> 
> This may be a good pattern to help customers use their existing AWS service catalog / service now, especially on provisioning resources aspect. There will be additional work in order to support operational actions for those resources. We will check how we can prioritize integration with Service Catalog and when can provide examples of that. Thank you again for your feedback and suggestions.

Thanks @z-sourcecode one potential path could be to leverage AWS Codestar to sync template files from GitHub documented [here](https://docs.aws.amazon.com/servicecatalog/latest/adminguide/git-synced-sc-products.html)

**Comment by z-sourcecode** [comment]
Closing this, currently not on the roadmap.
