### ISSUE TITLE
Installer fails with the following error - accept terms and subscribe - Gitlab

### ISSUE THREAD

**Issue by gowthamshankar99** [awslabs/app-development-for-backstage-io-on-aws#22]
7:23:52 PM | CREATE_FAILED        | AWS::EC2::Instance                            | GitlabHostingConstructGitlabHost08D9CB4A
In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/mark
etplace/pp?sku=4q59bftpyoueme916m1pjimec (Service: AmazonEC2; Status Code: 401; Error Code: OptInRequired; Request ID: fe9f7f71-91da-4
289-b14a-241c9b0c1a91; Proxy: null)

Can we add this info in the documentation to make sure the user accepts the terms before going through a failure ?

**Comment by z-sourcecode** [comment]
Hi @gowthamshankar99 Thanks for your feedback.
Marking this a documentation update.

**Comment by z-sourcecode** [comment]
Closing this issue as we released v0.2.1 which should address the issue describe
