### ISSUE TITLE
Need teardown instructions

### ISSUE THREAD

**Issue by doddatpivotal** [awslabs/app-development-for-backstage-io-on-aws#23]
Would like to see instructions for deleting a app once it has been created.

Would like to see steps to reverse install and tear down the deployment.

**Comment by z-sourcecode** [comment]
Hi @doddatpivotal Thanks for reaching out. Yes we have this feature in our list. we will try to priorities it and release it soon. thanks you for your feedback

**Comment by z-sourcecode** [comment]
We released v0.2.1 which now have delete apps, provider and resource capability built in
