### ISSUE TITLE
Terraform

### ISSUE THREAD

**Issue by jrwpatterson** [awslabs/app-development-for-backstage-io-on-aws#24]
Hi it's corporate policy to use terraform in our deployments.

All your code requires stacks any chance there is a way to run this without the stack requirement?

**Comment by jrwpatterson** [comment]
Sorry what I meant to say is when doing the annotations its looking for a stack but if we are just using a terra then that doesn't really work or am I wrong...

**Comment by acwatson** [comment]
I believe that only the serverless REST API application template uses the stack name from the annotations. If you are not using that application template specifically, you should be fine.

**Comment by z-sourcecode** [comment]
Hi @jrwpatterson We have released v0.2.1 of OPA on AWS plugins. We also have a complete terraform example in the code. Soon we will be releasing a youtube video dedicated to terraform provisioning.

https://github.com/awslabs/app-development-for-backstage-io-on-aws/tree/main/backstage-reference/common/tf_aws_ecs

https://github.com/awslabs/app-development-for-backstage-io-on-aws/tree/main/backstage-reference/templates/example-tf-nodejs

Thanks.
