### ISSUE TITLE
Unnecessary Gitlab plugin for non-Gitlab installations

### ISSUE THREAD

**Issue by jsundquist** [awslabs/app-development-for-backstage-io-on-aws#26]
Today I was trying out the plugins and ran into an issue that took me a while to figure out. It seems as though the `@aws/plugin-aws-apps-for-backstage` has a hard dependency on `@immobiliarelabs/backstage-plugin-gitlab`.

https://github.com/jsundquist/app-development-for-backstage-io-on-aws/blob/b4ca0946f083dd95272807c86e6c663ae5336dda/backstage-plugins/plugins/aws-apps/src/plugin.ts#L24-L37

Please consider removing the Gitlab gitlab plugin and related dependencies so the plugins can be used in projects that do not require Gitlab.

**Comment by z-sourcecode** [comment]
Hi @jsundquist thanks for your feedback. We currently do have a dependency on immobiliarelabs. In the next few days/weeks we will release a 2nd version of the solution with many more features. However, we have taken a dependency on gitlabs and as a result on immobiliarelabs plugin. We may change this in the future so customers can easily interchange their source control / CI/CD tools.

I'm tagging this as feature request.

**Comment by z-sourcecode** [comment]
Hi @jsundquist , Thanks for your response. that's correct. however we are about to release an updated release that will use gitlab in few places and in our core pipelines as well so at the moment we do have a dependency on gitlab.

**Comment by jsundquist** [comment]
Is there a reason for more gitlab integration? It feels as though then this plugin for Backstage will be discouraging users for GitHub or Bitbucket from using this particular plugin or resorting to forking it to make it more generic.

**Comment by z-sourcecode** [comment]
Yes, we built this a solution for a customer which asked this specifically. that being said , we will plan to accommodate other common CI/CD / SCM tools in the future.

**Comment by z-sourcecode** [comment]
New multi git support is now published on v0.3.4.
https://opaonaws.io/docs/integration/git

**Comment by oshriza** [comment]
> New multi git support is now published on v0.3.4. https://opaonaws.io/docs/integration/git

Hi @z-sourcecode , thank you for the new release with another git provider.
Is it possible to disable GitLab (in order to use GitHub) with this release (v0.3.4)?

Thanks.
