### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/@aws%2fplugin-aws-apps-backend-for-backstage: Not found"

### ISSUE THREAD

**Issue by hamzamaan** [awslabs/app-development-for-backstage-io-on-aws#5]
I am using these versions to deploy backstage-io on AWS.

yarn:     1.22.19
node:    18.16.0
npm:     9.5.1
jq:         1.6
cdk:       2.78.0
docker:  23.0.6

while installing the AWS Apps plugin and creating the backstage app, i am facing the error which is given below.
if anyone have resolution for this then let me know. Thanks

![image](https://github.com/awslabs/app-development-for-backstage-io-on-aws/assets/41535104/64f0fad6-8fcd-4949-b5af-fe858813eb22)

**Comment by z-sourcecode** [comment]
Hi @hamzamaan Thanks for your feedback, we just published the plugins to npmjs.org please pull the changes and try again. it should work now.

**Comment by hamzamaan** [comment]
Hi @z-sourcecode 
The above issue has been resolved. Now i am facing these issues. kindly check, Thanks

![image](https://github.com/awslabs/app-development-for-backstage-io-on-aws/assets/41535104/6c1b9843-278e-4623-9ef3-48036ae9d141)

![image](https://github.com/awslabs/app-development-for-backstage-io-on-aws/assets/41535104/db64af87-7f8d-4361-a59b-fc6f4654d570)



![image](https://github.com/awslabs/app-development-for-backstage-io-on-aws/assets/41535104/6db7af55-2be5-4de3-aa26-ffe96a011de4)

**Comment by z-sourcecode** [comment]
Hi @hamzamaan Can you kindly share the steps and at which point the failure occurs? also if you can share your node/npm/nvm/python version?

Can you confirm if you are able to do:
`npx @backstage/create-app@latest`
Thanks.

**Comment by awsjim** [comment]
Hi @hamzamaan  - I reproduced your behavior on a base Ubuntu 22 system.  Some of the node dependencies require node-gyp to install properly.  Can you verify that you've got the required pre-reqs for node-gyp? (see https://github.com/nodejs/node-gyp/blob/main/README.md)

I suspect that the most likely missing pre-req would be `gcc`.  This can be installed on Ubuntu via:
```sh
$ sudo apt install build-essential
```
If you can confirm that this fixes your error too, I'll get the pre-req documentation updated to reflect this.

Thanks for letting us know about this! 🙏

**Comment by awsjim** [comment]
Hi @hamzamaan  - based on further testing, additional changes were identified as required for Ubuntu/Linux systems.  Changes have been committed to the repo, so please ensure that you perform a new pull.  Thanks again for your feedback!

**Comment by z-sourcecode** [comment]
Closing the issue. Issue resolved.

**Comment by hamzamaan** [comment]
![image](https://github.com/awslabs/app-development-for-backstage-io-on-aws/assets/41535104/dd459369-0d29-44a4-b805-294385a7127b)

**Comment by z-sourcecode** [comment]
Closing the issue.  Issue resolved.
