### ISSUE TITLE
Github Integration 

### ISSUE THREAD

**Issue by hvegav** [awslabs/app-development-for-backstage-io-on-aws#57]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Integrate with GitHub and Githuba ctions 

#### Describe the solution you would like

Integrate the repository with github and the pipelines migrate to github actions 

#### Describe alternatives you have considered

I try to enable GitHub plugins and integration to backstage but realized that there are many parts that are related to gitlab especially the CI/CD

**Comment by z-sourcecode** [comment]
Hi @hvegav Thanks for submitting the request. We add GitHub integration(SCM abstraction) to our backlog and we will try to support it soon

**Comment by mbeacom** [comment]
@z-sourcecode  Any update on this roadmap item..?  Also, will this project be adopted for full-time support or will it remain an impact point kind of initiative? Thanks!

**Comment by dani-supercybex** [comment]
Hi @mbeacom Thanks for reaching out. 
We build and share this project as a result of working with customers. Our roadmap is impacted by the customers we work with. I can't say exactly when an abstraction for SCM will be published - but we did get this feedback from several customers.

We are releasing in the coming days a set of new features including: EKS support and importing VPCs. We are open for PRs by the community and also working on additional documentation(based on our [architecture](https://opaonaws.io/docs/techdocs/architecture)) that will provide specifications on how to submit PR

Thank you for your support

**Comment by z-sourcecode** [comment]
Hi @mbeacom Thanks for reaching out.
We build and share this project as a result of working with customers. Our roadmap is impacted by the customers we work with. I can't say exactly when an abstraction for SCM will be published - but we did get this feedback from several customers.

We are releasing in the coming days a set of new features including: EKS support and importing VPCs. We are open for PRs by the community and also working on additional documentation(based on our [architecture](https://opaonaws.io/docs/techdocs/architecture)) that will provide specifications on how to submit PR

Thank you for your support

**Comment by z-sourcecode** [comment]
Hi @mbeacom We are currently working with another customer to implement gitHub integration. Once we clean the artifacts we may publish few more assets that demonstrate integration with GitHub.
Thanks.

**Comment by jaredthivener** [comment]
are you also working on github enterprise?

**Comment by z-sourcecode** [comment]
Hi @jaredthivener , yes we are. 
We already built a multi-git support including github enterprise implementation. It will take us some time to release it but hopefully soon. Thanks.

**Comment by z-sourcecode** [comment]
Hi @victor-bpm we should have this available on the next release along with few other features and updates. I expect it to be release very soon , please stay tuned . Thanks

**Comment by z-sourcecode** [comment]
Github integration support is now published on v0.3.4. 
https://opaonaws.io/docs/integration/git
