### ISSUE TITLE
Fixed region defined in the 'existing eks cluster provider' ci cd template

### ISSUE THREAD

**Issue by stijnbrouwers** [awslabs/app-development-for-backstage-io-on-aws#78]
## Description

The CI/CD template for an existing EKS provider contains a hard-coded region (us-west-2).
**Impacted file:** backstage-reference/common/cicd/.gitlab-ci-aws-provider-eks.yml

- [/] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- OPA plugin versions [Required]: 0.3.1

## Reproduction Code [Required]

/

Create a new 'existing EKS provider' where the EKS cluster is in a different region than 'us-west-2' and the pipeline will fail.

## Expected behavior

Pipeline should succeed

## Actual behavior

Pipeline fails

**Comment by z-sourcecode** [comment]
Thanks @stijnbrouwers We appreciate your contribution and finding this issue!
